### ISSUE TITLE
Pre-launch balancing flow

### ISSUE THREAD

**Issue by Nuthen** [camchenry/super_shooter#15]
This is the last push before release 2.0.1. A lot of work has gone into this. Now we need to rebalance the game. This is a checklist of various things to adjust and balance before release. Feel free to add in anything. Each phase is the order in which something should be done, and the order for each listed item should be generally followed.

**Phase 1:**  Balance everything based on Blaster, since he is the "middle-ground" character. Don't worry about Megabyte yet. Focus on adjusting:
- [x] Blaster speed so that it feels good to move. Not too fast or too slow.
- [x] Damage so that it feels good to hit enemies (it takes enough hits to see their health decreasing)
- [ ] Bullet knock-back
- [x] Blob speed
- [x] Healer speed
- [x] Tank speed
- [x] Sweepers speed (I don't think the spawning or radius needs to be adjusted)
- [ ] Play test
- [ ] Enemy health as needed
- [ ] Enemy damage

**Phase 2:** Focus on adjusting values for Pathfinder and Berserker, so that they feel right with the balance already established based around Blaster. Focus on adjusting:
- [ ] Pathfinder values, so that it feels right with the balance already established around Blaster
- [ ] Berserker values

**Phase 3:** Waves
- [x] Balance the early waves. Have them introduce the enemies in an easy fashion, with waves that are homogeneous. 
- [x] Balance the later waves to combine all of the enemy types, ramping up in difficulty especially for waves 7-9

Proposed wave structure: wave 1 = blobs; wave 2 = sweepers; wave 3 = blobs + healers; wave 4 = blobs + healers + sweepers; wave 5 = tanks; wave 6 = tanks + blobs; wave 7 = tanks + blobs + healers; wave 8 = tanks + sweepers + healers; wave 9 = tanks + sweepers + healers + blobs; wave 10 = Megabyte

**Phase 4:** Megabyte
- [ ] Balance the Megabyte fight for all 3 characters, so that it can be beaten, but with a fair amount of difficulty

**Phase 5:** Highest of scores. Keep in mind that the enemy score values don't matter too much. But you should feel more rewarded for killing the larger enemies. Adjust score values for:
- [ ] Blobs
- [ ] Sweepers
- [ ] Tanks
- [ ] Healers
- [ ] Megabyte
- [ ] Accuracy score + bonus
- [ ] Time bonus
- [ ] Ricochet bonus

**Phase 6:** Final changes
- [ ] Change the version number for options
- [ ] Find our best high scores to add to the high score list

**Other:**
- [ ] Do something with the Other mode
- [x] Move drawing world lines to a DEBUG option
- [ ] Disable DEBUG

**Comment by Nuthen** [comment]
Blaster's speed of 1350 feels pretty good. Any lower feels sluggish. Any faster might negate the purpose of a faster character (Pathfinder)

**Comment by Nuthen** [comment]
Blaster's damage should be moved up to 40 (from 30). It kills Blobs in 3 shots, consistently.

**Comment by Nuthen** [comment]
Blobs given a knock-back resistance of -.1, so they are pushed back a tiny bit further when hit.
Slightly increased Blob speed
